name: Test & build "Create or Update RapidAPI Listing" GitHub Action

on:
  push:
    branches:
      - main
      - ncc
      
jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install modules
        run: npm install
        id: install
      - name: Run jest
        run: npm test
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: tool3/ncc@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        src: main/index.js
        branch: ncc
    - uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
